blank_issues_enabled: false

contact_links:
  - name: ValjangEngine proposals
    url: https://github.com/ValjangEngineengine/ValjangEngine-proposals
    about: Please submit feature proposals on the ValjangEngine proposals repository, not here.

  - name: ValjangEngine documentation repository
    url: https://github.com/ValjangEngineengine/ValjangEngine-docs
    about: Please report issues with documentation on the ValjangEngine documentation repository, not here.

  - name: ValjangEngine community channels
    url: https://ValjangEngineengine.org/community
    about: Please ask for technical support on one of the other community channels, not here.
