blank_issues_enabled: false

contact_links:
  - name: Godot proposals
    url: http://github.com/mehdigoom/ValjangEngine4.0.x-proposals
    about: Please submit feature proposals on the Godot proposals repository, not here.

  - name: Godot documentation repository
    url: http://github.com/mehdigoom/ValjangEngine4.0.x-docs
    about: Please report issues with documentation on the Godot documentation repository, not here.

  - name: Godot community channels
    url: http://Valjang.fr/community
    about: Please ask for technical support on one of the other community channels, not here.
